#!/usr/bin/python
import argparse
import json

from doppio import Doppio

parser = argparse.ArgumentParser(description="Command Line Interface for Mintpresso")
subparsers = parser.add_subparsers(help="sub-command help", dest='action')


parser_get = subparsers.add_parser('get', help='Get point, edges from mintpresso.')

parser_get.add_argument('--json', help="json data include information about a point. or edges")

# options for Point
parser_get.add_argument('--type', help="A type of point, it is REQUIRED to get a point. ")
parser_get.add_argument('--identifier', help="A identifier of point. it is REQUIRED to get point")

# options for Edges
parser_get.add_argument('--subjectId', help="A subjectId of edge.")
parser_get.add_argument('--subjectType', help="A subjectType of edge.")
parser_get.add_argument('--subjectIdentifier', help="A subjectIdentifier of edge.")
parser_get.add_argument('--verb', help="A verb of edge.")
parser_get.add_argument('--objectId', help="A objectId of edge.")
parser_get.add_argument('--objectType', help="A objectType of edge.")
parser_get.add_argument('--objectIdentifier', help="A ObjectIdentifier of edge.")

parser_set = subparsers.add_parser('set', help="Set point, edges to mintpresso.")

parser_set.add_argument('--json', help="json data include information about a point or edges.")

# options for Point
parser_set.add_argument('--type', help="A type of point, it is REQUIRED to set a point. ")
parser_set.add_argument('--identifier', help="A identifier of point. it is REQUIRED to set point")

# options for Edges
parser_set.add_argument('--subjectType', help="A subjectType of edge. it is REQUIRED to set a edge.")
parser_set.add_argument('--subjectIdentifier', help="A subjectIdentifier of edge. it is REQUIRED to set a edge.")
parser_set.add_argument('--verb', help="A verb of edge. it is REQUIRED to set a edge.")
parser_set.add_argument('--objectType', help="A objectType of edge. it is REQUIRED to set a edge.")
parser_set.add_argument('--objectIdentifier', help="A ObjectIdentifier of edge. it is REQUIRED to set a edge.")

parser_console = subparsers.add_parser('console', help='Console')


parser.add_argument("--token", type=str, 
                    help="Mintpresso API Token", required=True)


def main(args):
    doppio = Doppio(args.token)
    result = None
    if args.action == "console":
        print "Not Implemented yet."
    elif args.action == "get":
        print doppio.get("some-type", "some-identifier")
    elif args.action == "set":
        data = {}
        if not args.json is None:
            decoded = {}
            try:
                decoded = json.loads(args.json)
            except ValueError:
                print "`{0}` is not valid json".format(args.json)
                return None
            data = decoded
        elif not args.identifier is None and not args.type is None:
            data = {'type': args.type, 'identifier': args.identifier}
        elif not args.subjectId is None and not args.objectId is None:
            data = {'subjectId': args.subjectId,
                    'subjectType': '',
                    'subjectIdentifier': '',
                    'verb': args.verb,
                    'objectId': args.objectId,
                    'objectType': '',
                    'objectIdentifier': ''}
        elif not args.subjectType is None and \
             not args.subjectIdentifier is None and \
             not args.verb is None and \
             not args.objectType is None and \
             not args.objectIdentifier is None:
            data = {'subjectType': args.subjectType,
                    'subjectIdentifier': args.subjectIdentifier,
                    'verb': args.verb,
                    'objectType': args.objectType,
                    'objectIdentifier': args.objectIdentifier}
        result = doppio.set(**data)
    if not result is None:
        print result

if __name__ == "__main__":
    main(parser.parse_args())
